export const EXAM_SUBJECTS = [
  { id: "norsk",       label: "Norsk",                         short: "Norsk",          variants: null },
  { id: "matematikk",  label: "Matematikk",                    short: "Matte",          variants: [
    { id: "matematikk-1t", label: "1T",  desc: "Vg1 teoretisk" },
    { id: "matematikk-r1", label: "R1",  desc: "Vg2 realfag" },
    { id: "matematikk-r2", label: "R2",  desc: "Vg3 realfag" },
    { id: "matematikk-2p", label: "2P",  desc: "Vg2 praktisk" },
  ]},
  { id: "fysikk",      label: "Fysikk",                        short: "Fysikk",         variants: [
    { id: "fysikk-1", label: "Fysikk 1", desc: "Vg2" },
    { id: "fysikk-2", label: "Fysikk 2", desc: "Vg3" },
  ]},
  { id: "kjemi",       label: "Kjemi",                         short: "Kjemi",          variants: [
    { id: "kjemi-1", label: "Kjemi 1", desc: "Vg2" },
    { id: "kjemi-2", label: "Kjemi 2", desc: "Vg3" },
  ]},
  { id: "biologi",     label: "Biologi",                       short: "Biologi",        variants: [
    { id: "biologi-1", label: "Biologi 1", desc: "Vg2" },
    { id: "biologi-2", label: "Biologi 2", desc: "Vg3" },
  ]},
  { id: "historie",    label: "Historie",                      short: "Historie",       variants: null },
  { id: "naturfag",    label: "Naturfag",                      short: "Naturfag",       variants: null },
  { id: "samfunnsfag", label: "Samfunnskunnskap",              short: "Samfunn",        variants: null },
  { id: "engelsk",     label: "Engelsk",                       short: "Engelsk",        variants: null },
  { id: "geografi",    label: "Geografi",                      short: "Geografi",       variants: null },
  { id: "fransk",      label: "Fransk",                        short: "Fransk",         variants: [
    { id: "fransk-1", label: "Fransk 1", desc: "Vg2 Niveau I" },
    { id: "fransk-2", label: "Fransk 2", desc: "Vg3 Niveau II" },
  ]},
  { id: "tysk",        label: "Tysk",                          short: "Tysk",           variants: [
    { id: "tysk-1", label: "Tysk 1", desc: "Vg2 Nivå I" },
    { id: "tysk-2", label: "Tysk 2", desc: "Vg3 Nivå II" },
  ]},
  { id: "spansk",      label: "Spansk",                        short: "Spansk",         variants: [
    { id: "spansk-1", label: "Spansk 1", desc: "Vg2 Nivå I" },
    { id: "spansk-2", label: "Spansk 2", desc: "Vg3 Nivå II" },
  ]},
  { id: "samfunnsøkonomi", label: "Samfunnsøkonomi",          short: "Samf.øk.",       variants: [
    { id: "samfunnsøkonomi-1", label: "Samfunnsøkonomi 1", desc: "Vg2" },
    { id: "samfunnsøkonomi-2", label: "Samfunnsøkonomi 2", desc: "Vg3" },
  ]},
  { id: "sosiologi",   label: "Sosiologi og sosialantropologi", short: "Sosiologi",     variants: null },
  { id: "psykologi",   label: "Psykologi",                     short: "Psykologi",     variants: [
    { id: "psykologi-1", label: "Psykologi 1", desc: "Vg2" },
    { id: "psykologi-2", label: "Psykologi 2", desc: "Vg3" },
  ]},
  { id: "rettslære",   label: "Rettslære",                     short: "Rettslære",     variants: [
    { id: "rettslære-1", label: "Rettslære 1", desc: "Vg2" },
    { id: "rettslære-2", label: "Rettslære 2", desc: "Vg3" },
  ]},
  { id: "markedsføring", label: "Markedsføring og ledelse",   short: "Marked.",        variants: [
    { id: "markedsføring-1", label: "Markedsføring 1", desc: "Vg2" },
    { id: "markedsføring-2", label: "Markedsføring 2", desc: "Vg3" },
  ]},
  { id: "teknologi",   label: "Teknologi og forskningslære 1", short: "Teknologi",     variants: null },
  { id: "religion",    label: "Religion og etikk",             short: "Religion",      variants: null },
];

export const EXAM_TOPICS: Record<string, string[]> = {
  norsk:            ["Dramatikk og teater", "Retorikk og argumentasjon", "Norrøn litteratur", "Modernisme og samtid", "Språkhistorie", "Ibsen", "Hamsun", "Romantikken"],
  "matematikk-1t":  ["Algebra", "Lineære funksjoner", "Kvadratiske funksjoner", "Trigonometri", "Statistikk", "Kombinatorikk", "Eksponentialfunksjoner", "Logaritmer"],
  "matematikk-r1":  ["Derivasjon", "Integrasjon", "Vektorer", "Sinussetningen", "Cosinussetningen", "Kombinatorikk", "Rekker", "Grenseverdi"],
  "matematikk-r2":  ["Differensiallikninger", "Delbrøksoppspaltning", "Integrasjon per partes", "Matriser", "Egenverdier", "Komplekse tall", "Funksjonsdrøfting", "Tallteori"],
  "matematikk-2p":  ["Rente og lån", "Budsjett og økonomi", "Statistikk", "Sannsynlighet", "Areal og volum", "Trigonometri", "Lineære funksjoner", "Proporsjonalitet"],
  "fysikk-1":       ["Newtons lover", "Energi og arbeid", "Bevegelsesmengde", "Ohms lov", "Elektriske kretser", "Bølger og lyd", "Termodynamikk", "Gasslovene"],
  "fysikk-2":       ["Diffrakjon og interferens", "Faradays lov", "Induksjon", "Spesiell relativitet", "Tidsdilatasjon", "Bohr-modellen", "Fotoelektrisk effekt", "Radioaktivitet"],
  "kjemi-1":        ["Periodesystemet", "Elektronkonfigurasjon", "Ionebinding", "Kovalent binding", "pH og syrer", "Nøytralisering", "Redoks", "Organisk kjemi"],
  "kjemi-2":        ["Organiske reaksjonsmekanismer", "Kjemisk likevekt", "Le Chateliers prinsipp", "Elektrolyse", "Entalpi og entropi", "Gibbs energi", "Polymerer", "Biokjemi"],
  "biologi-1":      ["Cellemembranen", "Mitose og meiose", "DNA-replikasjon", "Transkripsjon og translasjon", "Nervesystemet", "Immunforsvaret", "Naturlig seleksjon", "Bioteknologi"],
  "biologi-2":      ["Krysningsanalyse", "Koppling og mutasjoner", "Antigen-antistoff", "T-celler og B-celler", "Hormonsystemet", "Populasjonsvekst", "Atferdsbiologi", "Reproduksjon"],
  historie:         ["Mellomkrigstiden", "Andre verdenskrig", "Den kalde krigen", "Industrialisering", "Kolonitiden", "Opplysningstiden", "Første verdenskrig", "FN og globalisering"],
  naturfag:         ["Celler og arv", "Bioteknologi", "Elektromagnetisme", "Stråling og radioaktivitet", "Klima og miljø", "Fornybar energi", "Kosmologi", "Bioteknologi"],
  samfunnsfag:      ["Demokrati og styresett", "Norsk økonomi", "FN og globalisering", "Menneskerettigheter", "Politiske systemer", "Media og ytringsfrihet", "Kriminalitet", "Velferdsstaten"],
  engelsk:          ["Literature analysis", "Grammar and writing", "Global issues", "British culture", "American culture", "Media and communication", "Science and technology", "Ethics"],
  geografi:         ["Klima og miljø", "Befolkningsvekst", "Ressurser og bærekraft", "Urbanisering", "Naturkatastrofer", "Geopolitikk", "Migrasjon", "Næringsgeografi"],
  "fransk-1":       ["Présentation personnelle et famille", "La vie quotidienne et l'école", "La gastronomie française", "Paris et les régions françaises", "Les loisirs et le sport", "La mode et les tendances"],
  "fransk-2":       ["Culture et identité française", "La Francophonie", "Littérature et cinéma français", "Société et politique en France", "L'environnement et le développement durable", "La jeunesse et les réseaux sociaux", "L'éducation en France", "La technologie et l'avenir"],
  "tysk-1":         ["Persönliche Vorstellung und Familie", "Schule und Alltag", "Freizeit und Hobbys", "Essen und Trinken", "Deutschland und deutschsprachige Länder", "Reisen und Urlaub", "Natur und Umwelt", "Berufe und Zukunft"],
  "tysk-2":         ["Deutsche Gesellschaft und Kultur", "Geschichte und Erinnerungskultur", "Die Europäische Union", "Umwelt und Nachhaltigkeit", "Jugend und Lebenswelt", "Migration und Integration", "Medien und Kommunikation", "Wirtschaft und Beruf"],
  "spansk-1":       ["Presentación personal y familia", "La escuela y la vida cotidiana", "El tiempo libre y los pasatiempos", "La comida y la gastronomía", "España y los países hispanohablantes", "Los viajes y el turismo", "El medio ambiente", "Los jóvenes y las redes sociales"],
  "spansk-2":       ["Cultura e identidad hispana", "Historia y política en el mundo hispano", "Medio ambiente y sostenibilidad", "Migración y globalización", "Jóvenes y redes sociales", "Literatura y cine hispanohablante", "Economía y trabajo", "Sociedad y diversidad"],
  "samfunnsøkonomi-1": ["Tilbud og etterspørsel", "Markedsmekanismen og prisdannelse", "Nasjonalregnskap og BNP", "Konjunktursvingninger", "Penge- og finanspolitikk", "Arbeidsledighet og inflasjon", "Offentlig sektor og skatter", "Internasjonal handel"],
  "samfunnsøkonomi-2": ["Fullkommen og ufullkommen konkurranse", "Markedssvikt og offentlige inngrep", "Fordelingspolitikk og velferd", "Valutamarkedet og valutapolitikk", "Miljøøkonomi og bærekraft", "Makroøkonomiske modeller", "Vekstteori og innovasjon", "Internasjonale finansmarkeder"],
  sosiologi:        ["Sosialisering og identitet", "Sosiale grupper og institusjoner", "Sosial ulikhet og stratifikasjon", "Kultur og kulturmøter", "Etnisitet og minoriteter", "Kjønn og kjønnsroller", "Sosial kontroll og avvik", "Globalisering og sosiale endringer"],
  "psykologi-1":    ["Sansing og persepsjon", "Klassisk og operant betinging", "Kognisjon og hukommelse", "Motivasjon og emosjoner", "Personlighet og personlighetsteorier", "Psykisk helse og psykiske lidelser", "Sosialpsykologi", "Biologisk psykologi"],
  "psykologi-2":    ["Kognitiv psykologi og informasjonsbehandling", "Utviklingspsykologi", "Klinisk psykologi og behandling", "Nevropsykologi og hjernen", "Positiv psykologi og mestring", "Stresspsykologi", "Psykologisk forskning og etikk", "Kulturpsykologi"],
  "rettslære-1":    ["Rettsstatens prinsipper og rettssystemet", "Rettskilder og lovgivning", "Avtaleretten", "Kjøpsretten og forbrukervern", "Erstatningsretten", "Strafferettens grunnbegreper", "Familieretten", "Arbeidsretten"],
  "rettslære-2":    ["Selskapsretten (AS, ANS, ENK)", "Immaterialretten", "Arbeidsrettens avtaleverk", "Forvaltningsretten", "Kontraktsrett og mislighold", "Kredittsikkerhet og panterett", "Internasjonal privatrett", "Strafferetten"],
  "markedsføring-1": ["Markedsføring og markedsmekanismer", "Markedsanalyse og segmentering", "Produkt og produktutvikling", "Pris og prisstrategier", "Distribusjon og salgsstrategi", "Markedskommunikasjon og reklame", "Digital markedsføring", "Bedriftsetikk og samfunnsansvar"],
  "markedsføring-2": ["Strategisk ledelse og SWOT-analyse", "Merkevarebygging", "Internasjonal markedsføring", "Ledelsesteorier og ledelsesstiler", "Prosjektledelse og teamarbeid", "Forretningsmodeller og innovasjon", "Budsjett og økonomiplanlegging", "Gründerskap"],
  teknologi:        ["Vitenskapelig metode og hypotesetesting", "Teknologiutvikling og samfunn", "Bærekraftig teknologi og grønn innovasjon", "Datateknologi og kunstig intelligens", "Bioteknologi og etikk", "Energiteknologi og fornybar energi", "Forsøksdesign og dataanalyse", "Teknologihistorie og fremtidsperspektiver"],
  religion:         ["Kristendom og kirkehistorie", "Islam", "Jødedom", "Hinduisme og buddhisme", "Ikke-religiøse livssyn (humanisme)", "Etikk og etiske teorier", "Religion og samfunn", "Nyreligiøsitet og new age"],
};

export const EXAM_CATEGORIES = [
  { label: "Realfag", ids: ["matematikk", "fysikk", "kjemi", "biologi", "naturfag", "teknologi"] },
  { label: "Språk", ids: ["norsk", "engelsk", "fransk", "tysk", "spansk"] },
  { label: "Samfunnsfag", ids: ["historie", "samfunnsfag", "geografi", "religion", "sosiologi"] },
  { label: "Økonomi og jus", ids: ["samfunnsøkonomi", "rettslære", "markedsføring", "psykologi"] },
];
